### ISSUE TITLE
Need feature to help toggle between hiding and showing an element in page

### ISSUE THREAD

**Issue by lasse-offerzen** [OfferZen-Community/developer-mentoring#157] opened 2022-09-19 08:53 UTC
We want one of our articles to have a button that hides/shows an answer (e.g., see this [example](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_toggle_hide_show))
<img width="703" alt="Screenshot 2022-09-19 at 10 50 57" src="https://user-images.githubusercontent.com/105852971/190982039-ae07c950-b0f8-4730-8989-0991c1a49677.png">

We would like to have this feature available four times on the same page. If anyone could help it would be greatly appreciated! Happy to provide more info if necessary 🚀🧠

**Comment by akshayishaan** [comment] 2022-09-19 09:38
Hey i want to work on this issue. Can we discuss?

**Comment by devluki** [comment] 2022-09-20 11:39
Hi, I would be happy to fix it, if you want you can assign it to me :)

**Comment by devluki** [comment] 2022-09-20 12:50
In which article you need to add this feature? Which sections needs to be hidden/shown?

**Comment by lasse-offerzen** [comment] 2022-09-20 12:56
Thanks so much for helping out @devluki ! We're looking at this article [here](https://www.developermentoring.guide/docs/meeting-with-your-mentoring-partner/mentoring-scenarios).

- We have four different scenarios in the article.
- We would like the reveal button to say 'Reveal Missing Ingredient'
- We would like all the information that follows before the next scenario to be revealed.

<img width="847" alt="Screenshot 2022-09-20 at 14 56 05" src="https://user-images.githubusercontent.com/105852971/191263514-f6245bb9-fadf-4f18-9991-e937df567456.png">

**Comment by devluki** [comment] 2022-09-24 15:11
It looks like I need a code review to deploy pull request, can I ask you @lasse-offerzen to perform it?

**Comment by lasse-offerzen** [comment] 2022-09-26 07:58
Hey @devluki ! I see there was a deployment error—let me check with the the owner of a Vercel project that builds this repo and send you the info

**Comment by lasse-offerzen** [comment] 2022-09-26 11:53
This was for you @devluki 

[13:55:55.853] Cloning [github.com/OfferZen-Community/developer-mentoring](http://github.com/OfferZen-Community/developer-mentoring) (Branch: toggle_show_hide_onClick, Commit: 8cde6eb)
[13:55:56.499] Cloning completed: 646.104ms
[13:55:56.885] Looking up build cache...
[13:56:00.751] Build cache downloaded [69.67 MB]: 3235.469ms
[13:56:00.797] Running “vercel build”
[13:56:01.277] Vercel CLI 28.4.2
[13:56:01.598] Warning: Due to “engines”: { “node”: “>=16.14.0" } in your `package.json` file, the Node.js Version defined in your Project Settings (“14.x”) will not apply. Learn More: http://vercel.link/node-version
[13:56:01.618] Installing dependencies...
[13:56:03.725]
[13:56:03.725] up to date in 2s
[13:56:03.725]
[13:56:03.726] 217 packages are looking for funding
[13:56:03.726]   run `npm fund` for details
[13:56:03.749] Detected `package-lock.json` generated by npm 7+...
[13:56:03.749] Running “npm run build”
[13:56:04.051]
[13:56:04.051] > poc-docusaurus@0.0.0 build
[13:56:04.051] > docusaurus build
[13:56:04.051]
[13:56:05.614] [INFO] [en] Creating an optimized production build...
[13:56:08.438] [info] [webpackbar] Compiling Client
[13:56:08.465] [info] [webpackbar] Compiling Server
[13:56:19.355] [success] [webpackbar] Client: Compiled with some errors in 10.92s
[13:56:19.359]
[13:56:19.359]
[13:56:19.360] Module not found: Error: Can’t resolve ‘./partials/_Scenario1.mdx’ in ‘/vercel/path0/src/components/MentoringScenarios’
[13:56:19.360] Module not found: Error: Can’t resolve ‘./partials/_Scenario2.mdx’ in ‘/vercel/path0/src/components/MentoringScenarios’
[13:56:19.360] Module not found: Error: Can’t resolve ‘./partials/_Scenario3.mdx’ in ‘/vercel/path0/src/components/MentoringScenarios’
[13:56:19.360] Module not found: Error: Can’t resolve ‘./partials/_Scenario4.mdx’ in ‘/vercel/path0/src/components/MentoringScenarios’
[13:56:19.360] [ERROR] Client bundle compiled with errors therefore further build is impossible.
[13:56:19.383] Error: Command “npm run build” exited with 1

**Comment by devluki** [comment] 2022-09-26 12:08
Hi, @lasse-offerzen, thanks for logs :). Should I do something more with this issue?

**Comment by lasse-offerzen** [comment] 2022-09-26 12:09
Yes please 🙏 If possible figure out why it's not merging?

**Comment by devluki** [comment] 2022-09-26 12:58
Ok, probably the deployment error is caused by syntax error in import statements (letter-casing inconsistencies). Partial .mdx files don't have capital letters in file names for eg. _scenario1.mdx. But in import statement they have 
 ``` 
import _Scenario1 from "./partials/_Scenario1.mdx";
```

The files couldn't be found the file at the declared path (check logs below)
```
 '[13:56:19.360] Module not found: Error: Can’t resolve ‘./partials/_Scenario1.mdx’ in ‘/vercel/path0/src/components/MentoringScenarios’
[13:56:19.360] Module not found: Error: Can’t resolve ‘./partials/_Scenario2.mdx’ in ‘/vercel/path0/src/components/MentoringScenarios’
[13:56:19.360] Module not found: Error: Can’t resolve ‘./partials/_Scenario3.mdx’ in ‘/vercel/path0/src/components/MentoringScenarios’
[13:56:19.360] Module not found: Error: Can’t resolve ‘./partials/_Scenario4.mdx’ in ‘/vercel/path0/src/components/MentoringScenarios’'
```

But how to fix it, should I make another pull request?

**Comment by lasse-offerzen** [comment] 2022-09-26 13:56
That would great! Yes please 🙏 @devluki

**Comment by devluki** [comment] 2022-09-26 16:42
@lasse-offerzen, I fixed letter casing in import statements and it looks like it is ok now ;).

**Comment by lasse-offerzen** [comment] 2022-09-27 07:08
Thank you so much @devluki ! You join our wall of fame! :D

**Closed** 2022-09-27 07:40 UTC
Labels: enhancement, good first issue, help wanted
